spring:
  cloud:
    stream:
      bindings:
        input:
          destination: MyExchange
          group: MyQueue
  
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    
  application:
    name: stream-consumer
    
server:
  port: 9091