spring:
  cloud:
    stream:
      bindings:
        PersonBinding:
          destination: MyExchange
        AnimalBinding:
          destination: MyExchange
          
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    
  application:
    name: stream-publisher
server:
  port: 9090